require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisabledByDefault: true
  Exclude:
    - "cypress/**/*"
    - "db/migrations/**/*.rb"
    - "docs/**/*"
    - "node_modules/**/*"
    - "private/**/*"
    - "public/**/*"
    - "static/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/EmptyLines:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: true

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/DescribedClass:
  EnforcedStyle: described_class

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
